$!THIS PROGRAM DISPLAYS THE STATUS OF ALL PRODUCTION QUEUES 11/11/94 GLB
$!DISPLAYS QUEUE INFO
$!12.6.95 GLB UPDATED CLEARSCREEN AND QUEUE QUERY
$ SET NOVERIFY
$ DISPLAY :== "WRITE SYS$OUTPUT"
$ SET CONTROL
$ LOOP1:
$ WRITE SYS$OUTPUT "[1;1H[2J"
$!=========================================
$! DISPLAY
$!=========================================
$ QUEUE= "PROD_HMO_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "PROD_SHHS_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "PROD_MCAR_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "PROD_LCSA_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "PROD_HGO_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "PROD_PCO_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "PROD_TPA_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "PROD_PAYR_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "PROD_ASO_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "RPTDB_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "HGS000_VIP_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "HGS000_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "HGS001_VIP_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "HGS001_BATCH"
$ GOSUB DISPLAY
$ QUEUE= "SYS$PRINT"
$ BLOCKS = F$GETQUI("DISPLAY_QUEUE","PENDING_JOB_BLOCK_COUNT","''QUEUE'")
$ HOLD = F$GETQUI("DISPLAY_QUEUE","HOLDING_JOB_COUNT","''QUEUE'")
$ EXEC = F$GETQUI("DISPLAY_QUEUE","EXECUTING_JOB_COUNT","''QUEUE'")
$ PEND = F$GETQUI("DISPLAY_QUEUE","PENDING_JOB_COUNT","''QUEUE'")
$ QNAME = F$GETQUI("DISPLAY_QUEUE","QUEUE_NAME","*''QUEUE'*","BATCH,SYMBIONT")
$ EXEC1 = F$GETQUI("DISPLAY_JOB","JOB_NAME",,"ALL_JOBS,EXECUTING_JOBS")
$ DISP = "''QUEUE'"+": EXEC "+F$STRING(EXEC)+" PEND: "+F$STRING(PEND)+","-
+F$STRING(BLOCKS)+" HOLD: "+F$STRING(HOLD)+ "->" + EXEC1
$ DISPLAY "''DISP'"

$ QUEUE= "DP350HC"
$ BLOCKS = F$GETQUI("DISPLAY_QUEUE","PENDING_JOB_BLOCK_COUNT","''QUEUE'")
$ HOLD = F$GETQUI("DISPLAY_QUEUE","HOLDING_JOB_COUNT","''QUEUE'")
$ EXEC = F$GETQUI("DISPLAY_QUEUE","EXECUTING_JOB_COUNT","''QUEUE'")
$ PEND = F$GETQUI("DISPLAY_QUEUE","PENDING_JOB_COUNT","''QUEUE'")
$ QNAME = F$GETQUI("DISPLAY_QUEUE","QUEUE_NAME","*''QUEUE'*","BATCH,SYMBIONT")
$ EXEC1 = F$GETQUI("DISPLAY_JOB","JOB_NAME",,"ALL_JOBS,EXECUTING_JOBS")
$ DISP = "''QUEUE'"+": EXEC "+F$STRING(EXEC)+" PEND: "+F$STRING(PEND)+","-
+F$STRING(BLOCKS)+" HOLD: "+F$STRING(HOLD)+ "->" + EXEC1
$ DISPLAY "''DISP'"
$ QUEUE= "INS$LAS6_PRINT"
$ BLOCKS = F$GETQUI("DISPLAY_QUEUE","PENDING_JOB_BLOCK_COUNT","''QUEUE'")
$ HOLD = F$GETQUI("DISPLAY_QUEUE","HOLDING_JOB_COUNT","''QUEUE'")
$ EXEC = F$GETQUI("DISPLAY_QUEUE","EXECUTING_JOB_COUNT","''QUEUE'")
$ PEND = F$GETQUI("DISPLAY_QUEUE","PENDING_JOB_COUNT","''QUEUE'")
$ QNAME = F$GETQUI("DISPLAY_QUEUE","QUEUE_NAME","*''QUEUE'*","BATCH,SYMBIONT")
$ EXEC1 = F$GETQUI("DISPLAY_JOB","JOB_NAME",,"ALL_JOBS,EXECUTING_JOBS")
$ DISP = "''QUEUE'"+": EXEC "+F$STRING(EXEC)+" PEND: "+F$STRING(PEND)+","-
+F$STRING(BLOCKS)+" HOLD: "+F$STRING(HOLD)+ "->" + EXEC1
$ DISPLAY "''DISP'"
$ DRIVE = "$1$DUA320"
$ FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$ MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$ IF (FREEBLOCKS .LE. 10000) THEN GOTO STOPIT
$ FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(SYSTEM)	"+F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$ DISPLAY FREE
$ DRIVE = "$1$DUA420"
$ FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$ MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$ IF (FREEBLOCKS .LE. 10000) THEN GOTO STOPIT
$ FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(DATA)	" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$ DISPLAY FREE
$! DRIVE = "$1$DUA430"
$! FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$! MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$! IF (FREEBLOCKS .LE. 10000) THEN GOTO STOPIT
$! FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(DATA)	" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$! DISPLAY FREE
$! DRIVE = "DSA620"
$! FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$! MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$! IF (FREEBLOCKS .LE. 10000) THEN GOTO STOPIT
$! FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(WP)		" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$! DISPLAY FREE
$! DRIVE = "DSA630"
$! FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$! MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$! IF (FREEBLOCKS .LE. 10000) THEN GOTO STOPIT
$! FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(WPMAIL)	" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$! DISPLAY FREE
$! DRIVE = "DSA700"
$! FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$! MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$! IF (FREEBLOCKS .LE. 10000) THEN GOTO STOPIT
$! FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(DATA)	" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$! DISPLAY FREE
$ DRIVE = "DSA710"
$ FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$ MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$ FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(LOGS AND REPORTS)	" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$ DISPLAY FREE
$ DRIVE = "DSA720"
$ FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$ MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$ IF (FREEBLOCKS .LE. 10000) THEN GOTO STOPIT
$ FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(RDB DATA)	" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$ DISPLAY FREE
$ DRIVE = "DSA730"
$ FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$ MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$ IF (FREEBLOCKS .LE. 10000) THEN GOTO STOPIT
$ FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(CLAIM DATA)	" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$ DISPLAY FREE
$ SKIPIT:
$ DRIVE = "$1$DIA0"
$ FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$ MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$ FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(SYSTEM DISK)	" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$ DISPLAY FREE
$ DRIVE = "$1$DKA0"
$ FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$ MAXBLOCKS  = F$GETDVI("''DRIVE'","MAXBLOCK")
$ FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(PROG AREA)	" +F$STRING(FREEBLOCKS*100/MAXBLOCKS)+ "%"
$ DISPLAY FREE
$! DRIVE = "$1$DIA3"
$! FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$! FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS (DCORPS SOURCE DISK)"
$! DISPLAY FREE
$! DRIVE = "$1$DIA4"
$! FREEBLOCKS = F$GETDVI("''DRIVE'","FREEBLOCKS")
$! FREE = "''DRIVE'="+F$STRING(FREEBLOCKS)+" BLOCKS(PROG SPACE)"
$! DISPLAY FREE
$ SH TI
$ WAIT 00:00:03
$ GOTO LOOP1
$ DISPLAY:
$ HOLD = F$GETQUI("DISPLAY_QUEUE","HOLDING_JOB_COUNT","''QUEUE'")
$ EXEC = F$GETQUI("DISPLAY_QUEUE","EXECUTING_JOB_COUNT","''QUEUE'")
$ PEND = F$GETQUI("DISPLAY_QUEUE","PENDING_JOB_COUNT","''QUEUE'")
$ QNAME = F$GETQUI("DISPLAY_QUEUE","QUEUE_NAME","*''QUEUE'*","BATCH")
$ DISP = "''QUEUE'"+": EXEC "+F$STRING(EXEC)+" PEND: "+F$STRING(PEND)+-
" HOLD: "+F$STRING(HOLD)+"''DESC'"
$ DISPLAY "''DISP'"
$ LOOPEXE:
$ EXEC = F$GETQUI("DISPLAY_JOB","JOB_NAME",,"ALL_JOBS,EXECUTING_JOBS")
$ IF (EXEC .NES. "") 
$    THEN
$    EXECE= F$GETQUI("DISPLAY_JOB","ENTRY_NUMBER",,"FREEZE_CONTEXT")
$    DISPLAY F$STRING(EXECE),"-E>"+EXEC
$ ENDIF
$ IF EXEC .NES. "" THEN GOTO LOOPEXE
$ RETURN
$ STOPIT:
$! STOP/QUEUE PROD_HMO_BATCH
$! STOP/QUEUE PROD_ASO_BATCH
$! STOP/QUEUE PROD_TPA_BATCH
$! STOP/QUEUE PROD_LCSA_BATCH
$! STOP/QUEUE PROD_HGO_BATCH
$! STOP/QUEUE PROD_MCAR_BATCH
$! STOP/QUEUE PROD_SHHS_BATCH
$! STOP/QUEUE PROD_PCO_BATCH
$! request/reply/to=oper10 "SYSTEM SPACE CRITICAL, LESS THAN 10,000 BLOCKS"
$LOOP2:
$GOTO LOOP2
$!PREVENT BREAK-OUT SHOULD IT BE RUN WITH NOCONTROL
